"""Add scan jobs table

Revision ID: 9c66817bb1e9
Revises: 29dab469bbc7
Create Date: 2026-10-03 07:26:57.324749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c66817bb1e9'
down_revision: Union[str, Sequence[str], None] = '29dab469bbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ports', 'cves')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ports', sa.Column('cves', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
