"""Init auth and findings models

Revision ID: e678565e6578
Revises: 
Create Date: 2026-10-03 07:18:05.480689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e678565e6578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hosts_ip'), 'hosts', ['ip'], unique=False)
    op.create_index(op.f('ix_hosts_report_id'), 'hosts', ['report_id'], unique=False)
    op.drop_constraint(op.f('hosts_report_id_fkey'), 'hosts', type_='foreignkey')
    op.create_foreign_key(None, 'hosts', 'scan_reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_ports_host_id'), 'ports', ['host_id'], unique=False)
    op.create_index('ix_ports_service_version', 'ports', ['service', 'version'], unique=False)
    op.drop_constraint(op.f('ports_host_id_fkey'), 'ports', type_='foreignkey')
    op.create_foreign_key(None, 'ports', 'hosts', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ports', 'cves')
    op.alter_column('scan_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('ports', sa.Column('cves', sa.TEXT(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ports', type_='foreignkey')
    op.create_foreign_key(op.f('ports_host_id_fkey'), 'ports', 'hosts', ['host_id'], ['id'])
    op.drop_index('ix_ports_service_version', table_name='ports')
    op.drop_index(op.f('ix_ports_host_id'), table_name='ports')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'hosts', type_='foreignkey')
    op.create_foreign_key(op.f('hosts_report_id_fkey'), 'hosts', 'scan_reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_hosts_report_id'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_ip'), table_name='hosts')
    # ### end Alembic commands ###
